name: On Push build and publish docker

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        # install dependencies
        
        pwd
        npm install
        # Run server
        
        node cateringServer.js &
        npm run test
        kill %1
    - uses: actions/checkout@master
    - name: Publish to Docker Repository
      id: publish
      uses: jerray/publish-docker-action@master
      with:
        name: cphjs/si
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
        repository: cphjs/si
        tags: ${{ github.sha }}
      env:
        CI: true
    - uses: steebchen/kubectl@master
      name: Deploy to kubernetes
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image --record deployment/catering-deployment catering=${{ github.repository }}:${{ github.sha }}